version: "2"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/:/var/log/nginx
        links:
            - php
    mariadb:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=replace_with_root_db_password
            - MYSQL_DATABASE=replace_with_wp_db_name
            - MYSQL_USER=replace_with_wp_db_user
            - MYSQL_PASSWORD=replace_with_wp_db_password
        volumes:
            #- ./database:/var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
        ports:
            - "9757:3306"
    php:
        #image: wordpress:php7.0-fpm
        build:
            context: .
            dockerfile: WpDockerfile
        ports:
            - 9000:9000
        volumes:
            - ./data/html:/var/www/html
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
        links:
            - mariadb:mysql
        environment:
            SKIP_SETUP: 'false' #set to true to skip setup after the first succesfoul boot
            WORDPRESS_DB_HOST: mariadb #change for remote development, otherwise do not touch it, it's a link'
            WORDPRESS_DB_USER: replace_with_wp_db_user
            WORDPRESS_DB_PASSWORD: replace_with_wp_db_password
            WORDPRESS_DB_NAME: replace_with_wp_db_name
            WORDPRESS_TABLE_PREFIX: replace_with_wp_table_prefix
            S3_UPLOADS_BUCKET: replace_with_s3_bucket
            S3_UPLOADS_KEY: replace_with_s3_key
            S3_UPLOADS_SECRET: replace_with_s3_secret
            S3_UPLOADS_REGION: replace_with_s3_region
            S3_UPLOADS_AUTOENABLE: 'false'
            SMTP_SERVER: replace_with_ses_smtp_url
            SMTP_USER: replace_with_ses_smtp_user
            SMTP_PASSWORD: replace_with_ses_smtp_password
            SMTP_ENC_TYPE: tls
            SMTP_PORT: 587
            SMTP_SENDER_NAME: replace_with_sitename
            SMTP_SENDER_EMAIL: replace_with_sender_email
            SMTP_ENVELOPE_SENDER_EMAIL: replace_with_sender_email
            SMTP_REPLY_TO_EMAIL: replace_with_replyto_email
            GOOGLE_TAG_ID: replace_with_googletagid #https://tagmanager.google.com/#/admin/accounts/create
            WP_SITEURL: http://localhost/ #keep the final slash
            ADMIN_EMAIL: info@studioup.it
            ADMIN_USER: replace_with_wp_admin_user
            ADMIN_PASSWORD: replace_with_wp_admin_pass
            PERMALINKS: '/%postname%/'
            WP_DEBUG_DISPLAY: 'true'
            WP_DEBUG_LOG: 'false'
            WP_DEBUG: 'false'
            PLUGINS: >-
                wp-example-content,
                codepress-admin-columns,
                [advanced-custom-fields-pro]http://studioup.it/wp_plugins/advanced-custom-fields-pro.zip --activate,
                advanced-custom-fields-font-awesome --activate,
                font-awesome-wp,
                amp --activate,
                wp-seo-acf-content-analysis --activate,
                seo-redirection,
                post-type-archive-links --activate,
                post-duplicator --activate,
                pdf-image-generator,
                regenerate-thumbnails,
                rewrite-rules-inspector,
                types --activate,
                wordpress-seo --activate,
                glue-for-yoast-seo-amp --activate,
                better-wp-security --activate,
                wp-mobile-detect,
                #ssh-sftp-updater-support
                postman-smtp --activate,
                [S3-Uploads]https://github.com/humanmade/S3-Uploads/archive/master.zip --activate,
                [formidable]http://studioup.it/wp_plugins/formidable-2.0.14.zip --activate,
                [sitepress-multilingual-cms]http://studioup.it/wp_plugins/sitepress-multilingual-cms.3.1.9.7.zip,
                [wpml-cms-nav]http://studioup.it/wp_plugins/wpml-cms-nav.1.4.7.zip,
                [wpml-media]http://studioup.it/wp_plugins/wpml-media.2.1.9.zip,
                [wpml-sticky-links]http://studioup.it/wp_plugins/wpml-sticky-links.1.3.9.zip,
                [wpml-string-translation]http://studioup.it/wp_plugins/wpml-string-translation.2.1.4.zip,
                [wpml-translation-management]http://studioup.it/wp_plugins/wpml-translation-management.1.9.11.zip,
                [formidable-wpml]http://studioup.it/wp_plugins/formidable-wpml-1.03.01.zip 
            THEMES: >-
                [cerulean]https://github.com/studioup/cerulean/archive/master.zip
            THEMENAME: 'client_theme'
            #SEARCH_REPLACE: yoursite.com,localhost:8080 #replace a string in db, only for specific needs
            MASK_THEME_URL: 'true'
    
    
